### ISSUE TITLE
Storybook: Add Storybook support to the app

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/wallora.com#36] opened 2021-05-09 07:49 UTC
This is a
[ ] bug
[ ] feature request
[x] documentation change
[ ] build/deploy enhancement request

Description:
To test that it works, create a story for the Header component

**Comment by hussamkhatib** [comment] 2021-05-09 11:06
This look like duplicate of #22

**Comment by souvikbasu** [comment] 2021-05-09 16:35
closing it as a duplicate

**Closed** 2021-05-09 16:35 UTC
